=== Rajatk95/pci_dss_ext_usb/cryptoService/src/main/resources/schema/vehicleRental.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"  >
  <xs:element name="vehicleRental">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="rentalInfo" />
        <xs:element ref="serviceReference"/>
        <xs:element ref="service"/>
        <xs:element ref="category"/>
        <xs:element ref="depoCode"/>
        <xs:element ref="pickUpCity"/>
        <xs:element ref="pickUpCountry"/>
        <xs:element ref="pickUpDepot"/>
        <xs:element ref="pickUpDate"/>
        <xs:element ref="dropUpDepot"/>
        <xs:element ref="dropUpDate"/>
        <xs:element ref="dates"/>
        <xs:element ref="units"/>
        <xs:element ref="paxTotal"/>
        <xs:element ref="paxAllocation"/>
        <xs:element ref="supplements"/>
        <xs:element ref="remarks"/>
        <xs:element ref="hints"/>
        <xs:element ref="flightInformation"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="rentalInfo" type="xs:string"/>
  <xs:element name="serviceReference" type="xs:string"/>
  <xs:element name="service" type="xs:string"/>
  <xs:element name="category" type="xs:string"/>
  <xs:element name="depoCode" type="xs:string"/>
  <xs:element name="pickUpCity" type="xs:string"/>
  <xs:element name="pickUpCountry" type="xs:string"/>
  <xs:element name="pickUpDepot" type="xs:string"/>
  <xs:element name="pickUpDate" type="xs:date"/>
  <xs:element name="dropUpDepot" type="xs:string"/>
  <xs:element name="dropUpDate" type="xs:date"/>
  <xs:element name="dates" type="xs:string"/>
  <xs:element name="units" type="xs:string"/>
  <xs:element name="paxTotal" type="xs:string"/>
  <xs:element name="paxAllocation">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="pax"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="pax" type="xs:string"/>
  <xs:element name="supplements">
    <xs:complexType/>
  </xs:element>
  <xs:element name="remarks">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="remark"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="remark" type="xs:string"/>
  <xs:element name="hints">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="hint"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="hint" type="xs:string"/>
  <xs:element name="flightInformation" type="xs:string"/>
</xs:schema>

=== Rajatk95/pci_dss_ext_usb/cryptoService/src/main/resources/schema/instance0.xml
<?xml version="1.0" encoding="UTF-8"?>
<vehicleRental xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/D:/workspace1/EmailNotificationService/schema/vehicleRental.xsd">
    <rentalInfo>New Service - Booking on Request (RQ)</rentalInfo>
    <serviceReference>3567231/12</serviceReference>
    <service>AVIS UAE (AEALLLXBUR)</service>
    <category>Intermediate 4 Door Auto Toyota Camry (ICAR)</category>
    <depoCode>A101</depoCode>
    <pickUpCity>Dubai</pickUpCity>
    <pickUpCountry>UAE</pickUpCountry>
    <pickUpDepot>Dubai International Airport DXB Terminal 1</pickUpDepot>
    <pickUpDate>15-Mar-08 / 13:10</pickUpDate>
    <dropUpDepot>Dubai International Airport DXB Terminal 1</dropUpDepot>
    <dropUpDate>18-Mar-08 / 13:10</dropUpDate>
    <dates>15Apr08 to 18Apr08 (3 Days)</dates>
    <units>1</units>
    <paxTotal>2 Adults</paxTotal>
    <paxAllocation>
        <pax>Mr Thomas/Joy  Adult (Sr No. 1)</pax>
        <pax>Mr Ashok/A  Adult (Sr No. 2)</pax>
        
    </paxAllocation>
    <supplements/>
    <remarks>
        <remark>Remarks from service lines</remark>
        
    </remarks>
    <hints>
        <hint>Hints from Package level</hint>
        <hint>Hints from Service level</hint>
        <hint>Hints from Category level</hint>
        <hint>Hints from Supplier level</hint>
    </hints>
    <flightInformation>EK545    MAA-DXB     EK 545    15Apr08 06:20 hrs   15Apr08 12:30 hrs</flightInformation>
</vehicleRental>
